# Generated by Django 4.2.7 on 2023-12-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectsapp", "0002_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="URL",
            field=models.URLField(
                default="https://github.com/DeepankTyagi2001?tab=repositories"
            ),
        ),
    ]
